
ALTER TABLE "BusinessMember" ADD COLUMN IF NOT EXISTS "canAddIncome" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "BusinessMember" ADD COLUMN IF NOT EXISTS "canAddExpense" BOOLEAN NOT NULL DEFAULT true;
